version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    groups:
      tauri:
        patterns:
          - "@tauri-apps/*"
      fortune-sheet:
        patterns:
          - "@fortune-sheet/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "build"
    groups:
      tauri:
        patterns:
          - "tauri"
          - "tauri-*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "ci"
